import React from "react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from "recharts";

function MonteCarloPathChart({ data = [], form = {} }) {
  if (!data || data.length === 0) {
    return (
      <div className="h-96 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-gradient-to-r from-indigo-500 to-blue-500 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
            </svg>
          </div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">
            Sample Price Paths
          </h3>
          <p className="text-gray-600 mb-4">
            Run a simulation to see sample stock price paths generated by the Monte Carlo simulation.
          </p>
          <div className="bg-indigo-50 rounded-lg p-4 border border-indigo-200">
            <p className="text-sm text-indigo-700">
              This chart will display a selection of simulated stock price paths, showing the stochastic nature
              of the underlying asset movement used in the option pricing calculation.
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Extract unique time points and path identifiers
  const timePoints = [...new Set(data.map(d => d.time))].sort((a, b) => a - b);
  const pathIds = [...new Set(data.map(d => d.path_id))];
  
  // Transform data for Recharts
  const chartData = timePoints.map(time => {
    const point = { time };
    pathIds.forEach(pathId => {
      const pathPoint = data.find(d => d.time === time && d.path_id === pathId);
      if (pathPoint) {
        point[`path_${pathId}`] = pathPoint.price;
      }
    });
    return point;
  });

  // Generate colors for different paths
  const colors = [
    "#8b5cf6", "#3b82f6", "#10b981", "#f59e0b", "#ef4444",
    "#8b5cf6", "#6366f1", "#06b6d4", "#84cc16", "#f97316"
  ];

  const formatTooltip = (value, name, props) => {
    if (name.startsWith('path_')) {
      return [`$${value.toFixed(2)}`, `Path ${name.split('_')[1]}`];
    }
    return [value, name];
  };

  const K = parseFloat(form.K) || 0;
  const S0 = parseFloat(form.S0) || 0;

  return (
    <div>
      <h3 className="text-lg font-semibold text-gray-900 mb-4">
        Sample Simulation Paths
      </h3>
      <p className="text-sm text-gray-600 mb-6">
        This chart shows a sample of the stock price paths generated during the Monte Carlo simulation.
        Each line represents one possible evolution of the stock price over time.
      </p>

      <div className="h-96">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart
            data={chartData}
            margin={{
              top: 20,
              right: 30,
              left: 20,
              bottom: 60,
            }}
          >
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis 
              dataKey="time"
              stroke="#6b7280"
              fontSize={12}
              tickFormatter={(value) => `${value.toFixed(2)}y`}
              label={{
                value: "Time to Expiry (years)",
                position: "insideBottom",
                offset: -10,
                style: { textAnchor: "middle", fill: "#6b7280", fontSize: "12px" }
              }}
            />
            <YAxis 
              stroke="#6b7280"
              fontSize={12}
              tickFormatter={(value) => `$${value.toFixed(0)}`}
              label={{
                value: "Stock Price ($)",
                angle: -90,
                position: "insideLeft",
                style: { textAnchor: "middle", fill: "#6b7280", fontSize: "12px" }
              }}
            />
            <Tooltip
              formatter={formatTooltip}
              labelFormatter={(value) => `Time: ${value.toFixed(3)} years`}
              contentStyle={{
                backgroundColor: "#ffffff",
                border: "1px solid #e5e7eb",
                borderRadius: "8px",
                boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
              }}
            />
            
            {/* Strike price reference line */}
            {K > 0 && (
              <ReferenceLine 
                y={K} 
                stroke="#ef4444" 
                strokeDasharray="8 8" 
                strokeWidth={2}
                label={{ value: `Strike: $${K}`, position: "insideTopRight" }}
              />
            )}
            
            {/* Initial stock price reference line */}
            {S0 > 0 && (
              <ReferenceLine 
                y={S0} 
                stroke="#10b981" 
                strokeDasharray="8 8" 
                strokeWidth={2}
                label={{ value: `S₀: $${S0}`, position: "insideTopLeft" }}
              />
            )}

            {/* Render path lines */}
            {pathIds.slice(0, 10).map((pathId, index) => (
              <Line
                key={pathId}
                type="monotone"
                dataKey={`path_${pathId}`}
                stroke={colors[index % colors.length]}
                strokeWidth={2}
                dot={false}
                strokeOpacity={0.7}
                connectNulls={false}
              />
            ))}
          </LineChart>
        </ResponsiveContainer>
      </div>

      <div className="mt-4 p-4 bg-gray-50 rounded-lg border">
        <h4 className="font-medium text-gray-800 mb-2">Path Analysis</h4>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm text-gray-600">
          <div>
            <strong>Geometric Brownian Motion:</strong> Each path follows the stochastic differential equation
            dS = μS dt + σS dW, where dW is a Wiener process.
          </div>
          <div>
            <strong>Reference Lines:</strong> The green dashed line shows the initial stock price (S₀),
            while the red line shows the strike price (K).
          </div>
          <div>
            <strong>Option Payoff:</strong> At expiry, the option value depends on where each path ends
            relative to the strike price.
          </div>
        </div>
      </div>
    </div>
  );
}

export default MonteCarloPathChart;